# Generated by Django 2.2.28 on 2022-11-16 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_addresscfcngknklf'),
    ]

    operations = [
        migrations.AddField(
            model_name='addresscfcngknklf',
            name='ca',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
